#------------------------------------
# GameMode Config File Version: 1.0
#------------------------------------

#ゲームモードを変更した際に表示されるメッセージ
#カラーコードが使用可能です

#ヘルプメッセージ
Help:
  Help1:
    - '&8[&b&lG&3&lM&8] &aRunning &bGameMode Version 1.0.0'
    - '&8[&b&lG&3&lM&8] &3サブコマンドを実行する権限がありません'
  Help2:
    - '&8[&b&lG&3&lM&8] &b/gm &e<0|1|2|3>'
  Error:
    - '&8[&b&lG&3&lM&8] &cあなたには権限がありません!'


#ゲームモードが変更されたときに表示するメッセージ
GameMode:
  SURVIVAL:
    - '&8[&b&lG&3&lM&8] &aゲームモードをサバイバルモードに変更しました'

  CREATIVE:
    - '&8[&b&lG&3&lM&8] &aゲームモードをクリエイティブモードに変更しました'

  ADVENTURE:
    - '&8[&b&lG&3&lM&8] &aゲームモードをアドベンチャーモードに変更しました'

  SPECTATOR:
    - '&8[&b&lG&3&lM&8] &aゲームモードをスペクテイターモードに変更しました'